// <auto-generated />
using System;
using BlazorIdle.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorIdle.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251011081425_InitializeEquipmentSystem")]
    partial class InitializeEquipmentSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BlazorIdle.Server.Domain.Activities.ActivityPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BattleStateJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExecutedSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("LimitType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LimitValue")
                        .HasColumnType("REAL");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivityPlans");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Agility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intellect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<DateTime?>("LastOfflineSettledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Profession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RosterOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Stamina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<int>("Strength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RosterOrder");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Equipment.Models.Affix", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedSlots")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_slots_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifierType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("RarityWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueMax")
                        .HasColumnType("REAL");

                    b.Property<double>("ValueMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ModifierType");

                    b.HasIndex("StatType");

                    b.ToTable("affixes", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Equipment.Models.GearDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedAffixPool")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_affix_pool_json");

                    b.Property<string>("ArmorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseStats")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_stats_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RarityWeights")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rarity_weights_json");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TierMultipliers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tier_multipliers_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequiredLevel");

                    b.HasIndex("SetId");

                    b.HasIndex("Slot");

                    b.ToTable("gear_definitions", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Equipment.Models.GearInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Affixes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("affixes_json");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RolledStats")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rolled_stats_json");

                    b.Property<string>("SetId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TierLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("IsEquipped");

                    b.HasIndex("Rarity");

                    b.HasIndex("CharacterId", "SlotType");

                    b.ToTable("gear_instances", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Equipment.Models.GearSet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bonuses")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bonuses_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pieces")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pieces_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("gear_sets", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.BattleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AttackIntervalSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DungeonId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DungeonRuns")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EnemyArmor")
                        .HasColumnType("REAL");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnemyMagicResist")
                        .HasColumnType("REAL");

                    b.Property<int>("EnemyMaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("KillTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<bool>("Killed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LootJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverkillDamage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SeedIndexEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SeedIndexStart")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpecialIntervalSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.BattleSegmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageBySourceJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageByTypeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EndTime")
                        .HasColumnType("REAL");

                    b.Property<int>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceFlowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RngIndexEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngIndexStart")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartTime")
                        .HasColumnType("REAL");

                    b.Property<string>("TagCountersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("BattleSegments");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.EconomyEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BattleId")
                        .HasFilter("BattleId IS NOT NULL");

                    b.HasIndex("CharacterId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("economy_events", (string)null);
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.RunningBattleSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Profession")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("SimulatedSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StepBattleId")
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StepBattleId")
                        .IsUnique();

                    b.ToTable("RunningBattleSnapshots");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.Character", b =>
                {
                    b.HasOne("BlazorIdle.Server.Domain.Characters.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.InventoryItem", b =>
                {
                    b.HasOne("BlazorIdle.Server.Domain.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Equipment.Models.GearInstance", b =>
                {
                    b.HasOne("BlazorIdle.Server.Domain.Equipment.Models.GearDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.BattleSegmentRecord", b =>
                {
                    b.HasOne("BlazorIdle.Server.Domain.Records.BattleRecord", null)
                        .WithMany("Segments")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Characters.User", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("BlazorIdle.Server.Domain.Records.BattleRecord", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
